version: 0.2

phases:
  pre_build:
    commands:
     - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 706109606549.dkr.ecr.ap-south-1.amazonaws.com)
      - REPOSITORY_URI=706109606549.dkr.ecr.ap-south-1.amazonaws.com/docker_ci_cd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo $IMAGE_TAG
      - echo $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls -al
      - docker --version
      - docker build -t docker_ci_cd .
      - echo $REPOSITORY_URI
      - echo $IMAGE_TAG
      - docker images
      - docker tag docker_ci_cd:latest 706109606549.dkr.ecr.ap-south-1.amazonaws.com/docker_ci_cd:$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 706109606549.dkr.ecr.ap-south-1.amazonaws.com/docker_ci_cd:$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
